export const advertisement = [
    { word: "advertisement", subcategory: "Campaigns" },
    { word: "advertising", subcategory: "Campaigns" },
    { word: "marketing", subcategory: "Campaigns" },
    { word: "promotion", subcategory: "Campaigns" },
    { word: "brand", subcategory: "Campaigns" },
    { word: "campaign", subcategory: "Campaigns" },
    { word: "target", subcategory: "Campaigns" },
    { word: "audience", subcategory: "Campaigns" },
    { word: "market", subcategory: "Campaigns" },
    { word: "customer", subcategory: "Campaigns" },
    { word: "consumer", subcategory: "Campaigns" },
    { word: "sales", subcategory: "Campaigns" },
    { word: "product", subcategory: "Campaigns" },
    { word: "service", subcategory: "Campaigns" },
    { word: "strategy", subcategory: "Campaigns" },
    { word: "tactic", subcategory: "Campaigns" },
    { word: "brand awareness", subcategory: "Campaigns" },
    { word: "branding", subcategory: "Campaigns" },
    { word: "pricing", subcategory: "Campaigns" },
    { word: "competitor", subcategory: "Campaigns" },
    { word: "competitive", subcategory: "Campaigns" },
    { word: "analysis", subcategory: "Campaigns" },
    { word: "segment", subcategory: "Campaigns" },
    { word: "segmentation", subcategory: "Campaigns" },
    { word: "positioning", subcategory: "Campaigns" },
    { word: "value", subcategory: "Campaigns" },
    { word: "unique selling proposition", subcategory: "Campaigns" },
    { word: "usp", subcategory: "Campaigns" },
    { word: "roi", subcategory: "Campaigns" },
    { word: "ctr", subcategory: "Campaigns" },
    { word: "cpc", subcategory: "Campaigns" },
    { word: "cpm", subcategory: "Campaigns" },
    { word: "lead", subcategory: "Opportunities" },
    { word: "conversion", subcategory: "Campaigns" },
    { word: "engagement", subcategory: "Campaigns" },
    { word: "content", subcategory: "Campaigns" },
    { word: "copy", subcategory: "Campaigns" },
    { word: "creative", subcategory: "Campaigns" },
    { word: "message", subcategory: "Campaigns" },
    { word: "targeting", subcategory: "Campaigns" },
    { word: "demographic", subcategory: "Campaigns" },
    { word: "psychographic", subcategory: "Campaigns" },
    { word: "behavioral", subcategory: "Campaigns" },
    { word: "market research", subcategory: "Campaigns" },
    { word: "survey", subcategory: "Campaigns" },
    { word: "focus group", subcategory: "Campaigns" },
    { word: "data", subcategory: "Campaigns" },
    { word: "analytics", subcategory: "Campaigns" },
    { word: "insights", subcategory: "Campaigns" },
    { word: "trends", subcategory: "Campaigns" },
    { word: "forecast", subcategory: "Opportunities" },
    { word: "opportunity", subcategory: "Opportunities" },
    { word: "challenges", subcategory: "Opportunities" },
    { word: "growth", subcategory: "Opportunities" },
    { word: "expansion", subcategory: "Opportunities" },
    { word: "position", subcategory: "Campaigns" },
    { word: "perception", subcategory: "Campaigns" },
    { word: "identity", subcategory: "Campaigns" },
    { word: "logo", subcategory: "Campaigns" },
    { word: "visual", subcategory: "Campaigns" },
    { word: "design", subcategory: "Campaigns" },
    { word: "color scheme", subcategory: "Campaigns" },
    { word: "font", subcategory: "Campaigns" },
    { word: "style", subcategory: "Campaigns" },
    { word: "website", subcategory: "Campaigns" },
    { word: "landing page", subcategory: "Campaigns" },
    { word: "social media", subcategory: "Campaigns" },
    { word: "influencer", subcategory: "Campaigns" },
    { word: "content marketing", subcategory: "Campaigns" },
    { word: "seo", subcategory: "Campaigns" },
    { word: "sem", subcategory: "Campaigns" },
    { word: "ppc", subcategory: "Campaigns" },
    { word: "smm", subcategory: "Campaigns" },
    { word: "smo", subcategory: "Campaigns" },
    { word: "email marketing", subcategory: "Subscription" },
    { word: "newsletter", subcategory: "Subscription" },
    { word: "direct mail", subcategory: "Subscription" },
    { word: "public relations", subcategory: "Campaigns" },
    { word: "press release", subcategory: "Campaigns" },
    { word: "media", subcategory: "Campaigns" },
    { word: "journalist", subcategory: "Campaigns" },
    { word: "editor", subcategory: "Campaigns" },
    { word: "publishing", subcategory: "Campaigns" },
    { word: "event", subcategory: "Campaigns" },
    { word: "sponsorship", subcategory: "Campaigns" },
    { word: "exhibition", subcategory: "Campaigns" },
    { word: "promotional event", subcategory: "Campaigns" },
    { word: "partnership", subcategory: "Campaigns" },
    { word: "collaboration", subcategory: "Campaigns" },
    { word: "endorsement", subcategory: "Campaigns" },
    { word: "testimonial", subcategory: "Campaigns" },
    { word: "referral", subcategory: "Campaigns" },
    { word: "customer loyalty", subcategory: "Campaigns" },
    { word: "customer satisfaction", subcategory: "Campaigns" },
    { word: "customer service", subcategory: "Campaigns" },
    { word: "customer retention", subcategory: "Campaigns" },
    { word: "lifetime value", subcategory: "Campaigns" },
    { word: "crm", subcategory: "Campaigns" },
    { word: "database", subcategory: "Campaigns" },
    { word: "lead generation", subcategory: "Opportunities" },
    { word: "lead nurturing", subcategory: "Opportunities" },
    { word: "inbound marketing", subcategory: "Campaigns" },
    { word: "outbound marketing", subcategory: "Campaigns" },
    { word: "b2b", subcategory: "Campaigns" },
    { word: "b2c", subcategory: "Campaigns" },
    { word: "customer journey", subcategory: "Campaigns" },
    { word: "touchpoint", subcategory: "Campaigns" },
    { word: "omnichannel", subcategory: "Campaigns" },
    { word: "mobile marketing", subcategory: "Campaigns" },
    { word: "app", subcategory: "Campaigns" },
    { word: "gamification", subcategory: "Campaigns" },
    { word: "viral", subcategory: "Campaigns" },
    { word: "shareability", subcategory: "Campaigns" },
    { word: "interactive", subcategory: "Campaigns" },
    { word: "engaging", subcategory: "Campaigns" },
    { word: "storytelling", subcategory: "Campaigns" },
    { word: "emotion", subcategory: "Campaigns" },
    { word: "humanize", subcategory: "Campaigns" },
    { word: "authenticity", subcategory: "Campaigns" },
    { word: "transparency", subcategory: "Campaigns" },
    { word: "trust", subcategory: "Campaigns" },
    { word: "test", subcategory: "Campaigns" },
    { word: "trial", subcategory: "Campaigns" },
    { word: "satisfaction", subcategory: "Campaigns" },
    { word: "experience", subcategory: "Campaigns" },
    { word: "feedback", subcategory: "Campaigns" },
    { word: "reviews", subcategory: "Campaigns" },
    { word: "testimonials", subcategory: "Campaigns" },
    { word: "case study", subcategory: "Campaigns" },
    { word: "social proof", subcategory: "Campaigns" },
    { word: "authority", subcategory: "Campaigns" },
    { word: "influence", subcategory: "Campaigns" },
    { word: "community", subcategory: "Campaigns" },
    { word: "networking", subcategory: "Campaigns" },
    { word: "participation", subcategory: "Campaigns" },
    { word: "collaborative", subcategory: "Campaigns" },
    { word: "referral program", subcategory: "Campaigns" },
    { word: "retargeting", subcategory: "Campaigns" },
    { word: "remarketing", subcategory: "Campaigns" },
    { word: "conversion rate optimization", subcategory: "Campaigns" },
    { word: "cro", subcategory: "Campaigns" },
    { word: "ab testing", subcategory: "Campaigns" },
    { word: "multivariate testing", subcategory: "Campaigns" },
    { word: "usability", subcategory: "Campaigns" },
    { word: "user experience", subcategory: "Campaigns" },
    { word: "user interface", subcategory: "Campaigns" },
    { word: "ui", subcategory: "Campaigns" },
    { word: "uX", subcategory: "Campaigns" },
    { word: "accessibility", subcategory: "Campaigns" },
    { word: "responsive design", subcategory: "Campaigns" },
    { word: "mobile optimization", subcategory: "Campaigns" },
    { word: "localization", subcategory: "Campaigns" },
    { word: "globalization", subcategory: "Campaigns" },
    { word: "integrated marketing communications", subcategory: "Campaigns" },
    { word: "imc", subcategory: "Campaigns" },
    { word: "pr campaign", subcategory: "Campaigns" },
    { word: "corporate communication", subcategory: "Campaigns" },
    { word: "crisis communication", subcategory: "Campaigns" },
    { word: "influencer marketing", subcategory: "Campaigns" },
    { word: "micro-influencer", subcategory: "Campaigns" },
    { word: "thought leadership", subcategory: "Campaigns" },
    { word: "co-branding", subcategory: "Campaigns" },
    { word: "loyalty program", subcategory: "Campaigns" },
    { word: "discount", subcategory: "Campaigns" },
    { word: "promotional offer", subcategory: "Campaigns" },
    { word: "sales promotion", subcategory: "Campaigns" },
    { word: "in-store promotion", subcategory: "Campaigns" },
    { word: "point of sale", subcategory: "Campaigns" },
    { word: "distribution", subcategory: "Campaigns" },
    { word: "logistics", subcategory: "Campaigns" },
    { word: "supply chain", subcategory: "Campaigns" },
    { word: "warehouse", subcategory: "Campaigns" },
    { word: "inventory", subcategory: "Campaigns" },
    { word: "stock", subcategory: "Campaigns" },
    { word: "fulfillment", subcategory: "Campaigns" },
    { word: "shipping", subcategory: "Campaigns" },
    { word: "delivery", subcategory: "Campaigns" },
    { word: "return policy", subcategory: "Campaigns" },
    { word: "packaging", subcategory: "Campaigns" },
    { word: "environmental sustainability", subcategory: "Campaigns" },
    { word: "corporate social responsibility", subcategory: "Campaigns" },
    { word: "csr", subcategory: "Campaigns" },
    { word: "green marketing", subcategory: "Campaigns" },
    { word: "ethical", subcategory: "Campaigns" },
    { word: "authentic", subcategory: "Campaigns" },
    { word: "story-driven", subcategory: "Campaigns" },
    { word: "association", subcategory: "Campaigns" },
    { word: "event sponsorship", subcategory: "Campaigns" },
    { word: "trade show", subcategory: "Campaigns" },
    { word: "networking event", subcategory: "Campaigns" },
    { word: "keynote", subcategory: "Campaigns" },
    { word: "speaker", subcategory: "Campaigns" },
    { word: "panel discussion", subcategory: "Campaigns" },
    { word: "workshop", subcategory: "Campaigns" },
    { word: "demonstration", subcategory: "Campaigns" },
    { word: "tutorial", subcategory: "Campaigns" },
    { word: "collateral", subcategory: "Campaigns" },
    { word: "brochure", subcategory: "Campaigns" },
    { word: "flyer", subcategory: "Campaigns" },
    { word: "poster", subcategory: "Campaigns" },
    { word: "banner", subcategory: "Campaigns" },
    { word: "ad copy", subcategory: "Campaigns" },
    { word: "tagline", subcategory: "Campaigns" },
    { word: "slogan", subcategory: "Campaigns" },
    { word: "call to action", subcategory: "Campaigns" },
    { word: "landing page optimization", subcategory: "Campaigns" },
    { word: "lead magnet", subcategory: "Opportunities" },
    { word: "whitepaper", subcategory: "Campaigns" },
    { word: "e-book", subcategory: "Campaigns" },
    { word: "infographic", subcategory: "Campaigns" },
    { word: "explainer video", subcategory: "Campaigns" },
    { word: "tutorial video", subcategory: "Campaigns" },
    { word: "webinar", subcategory: "Campaigns" },
    { word: "podcast", subcategory: "Campaigns" },
    { word: "customization", subcategory: "Campaigns" },
    { word: "personalization", subcategory: "Campaigns" },
    { word: "Subscription", subcategory: "Subscription" },
    { word: "membership", subcategory: "Subscription" },
    { word: "vip", subcategory: "Subscription" },
    { word: "exclusive", subcategory: "Subscription" },
    { word: "early access", subcategory: "Subscription" },
    { word: "limited edition", subcategory: "Subscription" },
    { word: "seasonal promotion", subcategory: "Campaigns" },
    { word: "holiday campaign", subcategory: "Campaigns" },
    { word: "back-to-school sale", subcategory: "Campaigns" },
    { word: "black friday", subcategory: "Campaigns" },
    { word: "cyber monday", subcategory: "Campaigns" },
    { word: "christmas special", subcategory: "Campaigns" },
    { word: "new year's offer", subcategory: "Campaigns" },
    { word: "spring sale", subcategory: "Campaigns" },
    { word: "summer promotion", subcategory: "Campaigns" },
    { word: "fall discount", subcategory: "Campaigns" },
    { word: "winter clearance", subcategory: "Campaigns" },
    { word: "anniversary celebration", subcategory: "Campaigns" },
    { word: "milestone", subcategory: "Campaigns" },
    { word: "launch", subcategory: "Campaigns" },
    { word: "pre-launch", subcategory: "Campaigns" },
    { word: "post-launch", subcategory: "Campaigns" },
    { word: "re-launch", subcategory: "Campaigns" },
    { word: "guerilla marketing", subcategory: "Campaigns" },
    { word: "ambient marketing", subcategory: "Campaigns" },
    { word: "experiential marketing", subcategory: "Campaigns" },
    { word: "event marketing", subcategory: "Campaigns" },
    { word: "influencer collaboration", subcategory: "Campaigns" },
    { word: "brand ambassador", subcategory: "Campaigns" },
    { word: "product placement", subcategory: "Campaigns" },
    { word: "sponsorship deal", subcategory: "Campaigns" },
    { word: "advertorial", subcategory: "Campaigns" },
    { word: "native advertising", subcategory: "Campaigns" },
    { word: "brand identity", subcategory: "Campaigns" },
    { word: "brand loyalty", subcategory: "Campaigns" },
    { word: "customer acquisition", subcategory: "Campaigns" },
    { word: "customer engagement", subcategory: "Campaigns" },
    { word: "customer empowerment", subcategory: "Campaigns" },
    { word: "brand positioning", subcategory: "Campaigns" },
    { word: "creative", subcategory: "Campaigns" },
    { word: "innovation", subcategory: "Campaigns" },
    { word: "digital", subcategory: "Campaigns" },
    { word: "interactive", subcategory: "Campaigns" },
    { word: "engagement", subcategory: "Campaigns" },
    { word: "content", subcategory: "Campaigns" },
    { word: "campaign", subcategory: "Campaigns" },
    { word: "strategy", subcategory: "Campaigns" },
    { word: "target", subcategory: "Campaigns" },
    { word: "audience", subcategory: "Campaigns" },
    { word: "brand", subcategory: "Campaigns" },
    { word: "promotion", subcategory: "Campaigns" },
    { word: "advertisement", subcategory: "Campaigns" },
    { word: "marketing", subcategory: "Campaigns" },
    { word: "sales", subcategory: "Campaigns" },
    { word: "consumer", subcategory: "Campaigns" },
    { word: "customer", subcategory: "Campaigns" },
    { word: "market", subcategory: "Campaigns" },
    { word: "segment", subcategory: "Campaigns" },
    { word: "positioning", subcategory: "Campaigns" },
    { word: "value", subcategory: "Campaigns" },
    { word: "competitor", subcategory: "Campaigns" },
    { word: "analysis", subcategory: "Campaigns" },
    { word: "trends", subcategory: "Campaigns" },
    { word: "insights", subcategory: "Campaigns" },
    { word: "roi", subcategory: "Campaigns" },
    { word: "cpc", subcategory: "Campaigns" },
    { word: "cpm", subcategory: "Campaigns" },
    { word: "lead", subcategory: "Opportunities" },
    { word: "conversion", subcategory: "Campaigns" },
    { word: "seo", subcategory: "Campaigns" },
    { word: "sem", subcategory: "Campaigns" },
    { word: "smm", subcategory: "Campaigns" },
    { word: "email marketing", subcategory: "Subscription" },
    { word: "crm", subcategory: "Campaigns" },
    { word: "database", subcategory: "Campaigns" },
    { word: "referral", subcategory: "Campaigns" },
    { word: "feedback", subcategory: "Campaigns" },
    { word: "reviews", subcategory: "Campaigns" },
    { word: "testimonials", subcategory: "Campaigns" },
    { word: "social proof", subcategory: "Campaigns" },
    { word: "influence", subcategory: "Campaigns" },
    { word: "community", subcategory: "Campaigns" },
    { word: "networking", subcategory: "Campaigns" },
    { word: "collaboration", subcategory: "Campaigns" },
    { word: "influencer", subcategory: "Campaigns" },
    { word: "engaging", subcategory: "Campaigns" },
    { word: "storytelling", subcategory: "Campaigns" },
    { word: "authenticity", subcategory: "Campaigns" },
    { word: "trust", subcategory: "Campaigns" },
    { word: "customer journey", subcategory: "Campaigns" },
    { word: "omnichannel", subcategory: "Campaigns" },
    { word: "mobile marketing", subcategory: "Campaigns" },
    { word: "app", subcategory: "Campaigns" },
    { word: "viral", subcategory: "Campaigns" },
    { word: "interactive", subcategory: "Campaigns" },
    { word: "gamification", subcategory: "Campaigns" },
    { word: "usability", subcategory: "Campaigns" },
    { word: "user experience", subcategory: "Campaigns" },
    { word: "accessibility", subcategory: "Campaigns" },
    { word: "localization", subcategory: "Campaigns" },
    { word: "globalization", subcategory: "Campaigns" },
    { word: "integrated marketing communications", subcategory: "Campaigns" },
    { word: "pr campaign", subcategory: "Campaigns" },
    { word: "crisis communication", subcategory: "Campaigns" },
    { word: "micro-influencer", subcategory: "Campaigns" },
    { word: "thought leadership", subcategory: "Campaigns" },
    { word: "loyalty program", subcategory: "Campaigns" },
    { word: "promotional offer", subcategory: "Campaigns" },
    { word: "sales promotion", subcategory: "Campaigns" },
    { word: "distribution", subcategory: "Campaigns" },
    { word: "logistics", subcategory: "Campaigns" },
    { word: "inventory", subcategory: "Campaigns" },
    { word: "fulfillment", subcategory: "Campaigns" },
    { word: "packaging", subcategory: "Campaigns" },
    { word: "corporate social responsibility", subcategory: "Campaigns" },
    { word: "ethical", subcategory: "Campaigns" },
    { word: "association", subcategory: "Campaigns" },
    { word: "trade show", subcategory: "Campaigns" },
    { word: "networking event", subcategory: "Campaigns" },
    { word: "keynote", subcategory: "Campaigns" },
    { word: "speaker", subcategory: "Campaigns" },
    { word: "workshop", subcategory: "Campaigns" },
    { word: "tutorial", subcategory: "Campaigns" },
    { word: "collateral", subcategory: "Campaigns" },
    { word: "brochure", subcategory: "Campaigns" },
    { word: "flyer", subcategory: "Campaigns" },
    { word: "poster", subcategory: "Campaigns" },
    { word: "ad copy", subcategory: "Campaigns" },
    { word: "tagline", subcategory: "Campaigns" },
    { word: "slogan", subcategory: "Campaigns" },
    { word: "call to action", subcategory: "Campaigns" },
    { word: "landing page optimization", subcategory: "Campaigns" },
    { word: "e-book", subcategory: "Campaigns" },
    { word: "infographic", subcategory: "Campaigns" },
    { word: "explainer video", subcategory: "Campaigns" },
    { word: "tutorial video", subcategory: "Campaigns" },
    { word: "webinar", subcategory: "Campaigns" },
    { word: "podcast", subcategory: "Campaigns" },
    { word: "personalization", subcategory: "Campaigns" },
    { word: "Subscription", subcategory: "Subscription" },
    { word: "membership", subcategory: "Subscription" },
    { word: "vip", subcategory: "Subscription" },
    { word: "exclusive", subcategory: "Subscription" },
    { word: "limited edition", subcategory: "Subscription" },
    { word: "seasonal promotion", subcategory: "Campaigns" },
    { word: "anniversary celebration", subcategory: "Campaigns" },
    { word: "milestone", subcategory: "Campaigns" },
    { word: "launch", subcategory: "Campaigns" },
    { word: "guerilla marketing", subcategory: "Campaigns" },
    { word: "ambient marketing", subcategory: "Campaigns" },
    { word: "experiential marketing", subcategory: "Campaigns" },
    { word: "event marketing", subcategory: "Campaigns" },
    { word: "brand ambassador", subcategory: "Campaigns" },
    { word: "product placement", subcategory: "Campaigns" },
    { word: "sponsorship deal", subcategory: "Campaigns" },
    { word: "advertorial", subcategory: "Campaigns" },
    { word: "native advertising", subcategory: "Campaigns" },
    { word: "brand identity", subcategory: "Campaigns" },
    { word: "brand loyalty", subcategory: "Campaigns" },
    { word: "customer acquisition", subcategory: "Campaigns" },
    { word: "customer engagement", subcategory: "Campaigns" },
    { word: "customer empowerment", subcategory: "Campaigns" },
    { word: "brand positioning", subcategory: "Campaigns" },
    { word: "creative", subcategory: "Campaigns" },
    { word: "innovation", subcategory: "Campaigns" },
    { word: "digital", subcategory: "Campaigns" },
    { word: "interactive", subcategory: "Campaigns" },
    { word: "engagement", subcategory: "Campaigns" },
    { word: "content", subcategory: "Campaigns" },
    { word: "campaign", subcategory: "Campaigns" },
    { word: "strategy", subcategory: "Campaigns" },
    { word: "target", subcategory: "Campaigns" },
    { word: "audience", subcategory: "Campaigns" },
    { word: "brand", subcategory: "Campaigns" },
    { word: "promotion", subcategory: "Campaigns" },
    { word: "advertisement", subcategory: "Campaigns" },
    { word: "marketing", subcategory: "Campaigns" },
    { word: "sales", subcategory: "Campaigns" },
    { word: "consumer", subcategory: "Campaigns" },
    { word: "customer", subcategory: "Campaigns" },
    { word: "market", subcategory: "Campaigns" },
    { word: "segment", subcategory: "Campaigns" },
    { word: "value", subcategory: "Campaigns" },
    { word: "competitor", subcategory: "Campaigns" },
    { word: "analysis", subcategory: "Campaigns" },
    { word: "trends", subcategory: "Campaigns" },
    { word: "insights", subcategory: "Campaigns" },
    { word: "roi", subcategory: "Campaigns" },
    { word: "cpc", subcategory: "Campaigns" },
    { word: "cpm", subcategory: "Campaigns" },
    { word: "conversion", subcategory: "Campaigns" },
    { word: "seo", subcategory: "Campaigns" },
    { word: "sem", subcategory: "Campaigns" },
    { word: "smm", subcategory: "Campaigns" },
    { word: "email marketing", subcategory: "Subscription" },
    { word: "crm", subcategory: "Campaigns" },
    { word: "database", subcategory: "Campaigns" },
    { word: "referral", subcategory: "Campaigns" },
    { word: "feedback", subcategory: "Campaigns" },
    { word: "reviews", subcategory: "Campaigns" },
    { word: "testimonials", subcategory: "Campaigns" },
    { word: "social proof", subcategory: "Campaigns" },
    { word: "influence", subcategory: "Campaigns" },
    { word: "community", subcategory: "Campaigns" },
    { word: "networking", subcategory: "Campaigns" },
    { word: "collaboration", subcategory: "Campaigns" },
    { word: "influencer", subcategory: "Campaigns" },
    { word: "engaging", subcategory: "Campaigns" },
    { word: "storytelling", subcategory: "Campaigns" },
    { word: "authenticity", subcategory: "Campaigns" },
    { word: "trust", subcategory: "Campaigns" },
    { word: "customer journey", subcategory: "Campaigns" },
    { word: "omnichannel", subcategory: "Campaigns" },
    { word: "mobile marketing", subcategory: "Campaigns" },
    { word: "app", subcategory: "Campaigns" },
    { word: "viral", subcategory: "Campaigns" },
    { word: "interactive", subcategory: "Campaigns" },
    { word: "gamification", subcategory: "Campaigns" }
  ]
  