export const news = [
    { word: "news", subcategory: "General News" },
    { word: "headline", subcategory: "General News" },
    { word: "update", subcategory: "General News" },
    { word: "bulletin", subcategory: "General News" },
    { word: "story", subcategory: "General News" },
    { word: "coverage", subcategory: "General News" },
    { word: "journalism", subcategory: "General News" },
    { word: "press", subcategory: "General News" },
    { word: "publication", subcategory: "General News" },
    { word: "broadcast", subcategory: "General News" },
    { word: "telecast", subcategory: "General News" },
    { word: "newscast", subcategory: "General News" },
    { word: "feature", subcategory: "General News" },
    { word: "column", subcategory: "General News" },
    { word: "editorial", subcategory: "General News" },
    { word: "commentary", subcategory: "General News" },
    { word: "op-ed", subcategory: "General News" },
    { word: "analysis", subcategory: "General News" },
    { word: "reviews", subcategory: "General News" },
    { word: "critique", subcategory: "General News" },
    { word: "investigative", subcategory: "General News" },
    { word: "breaking news", subcategory: "General News" },
    { word: "exclusive", subcategory: "General News" },
    { word: "scoop", subcategory: "General News" },
    { word: "briefing", subcategory: "General News" },
    { word: "dispatch", subcategory: "General News" },
    { word: "newsflash", subcategory: "General News" },
    { word: "report", subcategory: "General News" },
    { word: "summary", subcategory: "General News" },
    { word: "recap", subcategory: "General News" },
    { word: "notification", subcategory: "General News" },
    { word: "announcement", subcategory: "General News" },
    { word: "newsfeed", subcategory: "General News" },
    { word: "stream", subcategory: "General News" },
    { word: "wire", subcategory: "General News" },
    { word: "agency", subcategory: "General News" },
    { word: "correspondent", subcategory: "General News" },
    { word: "reporter", subcategory: "General News" },
    { word: "journalist", subcategory: "General News" },
    { word: "editor", subcategory: "General News" },
    { word: "anchor", subcategory: "General News" },
    { word: "broadcaster", subcategory: "General News" },
    { word: "newsreader", subcategory: "General News" },
    { word: "presenter", subcategory: "General News" },
    { word: "commentator", subcategory: "General News" },
    { word: "analyst", subcategory: "General News" },
    { word: "expert", subcategory: "General News" },
    { word: "interview", subcategory: "General News" },
    { word: "statement", subcategory: "General News" },
    { word: "source", subcategory: "General News" },
    { word: "insider", subcategory: "General News" },
    { word: "witness", subcategory: "General News" },
    { word: "byline", subcategory: "General News" },
    { word: "dateline", subcategory: "General News" },
    { word: "tagline", subcategory: "General News" },
    { word: "headline", subcategory: "General News" },
    { word: "subhead", subcategory: "General News" },
    { word: "lead", subcategory: "General News" },
    { word: "paragraph", subcategory: "General News" },
    { word: "quote", subcategory: "General News" },
    { word: "soundbite", subcategory: "General News" },
    { word: "clip", subcategory: "General News" },
    { word: "footage", subcategory: "General News" },
    { word: "image", subcategory: "General News" },
    { word: "photograph", subcategory: "General News" },
    { word: "graphic", subcategory: "General News" },
    { word: "infographic", subcategory: "General News" },
    { word: "chart", subcategory: "General News" },
    { word: "map", subcategory: "General News" },
    { word: "illustration", subcategory: "General News" },
    { word: "caption", subcategory: "General News" },
    { word: "sidebar", subcategory: "General News" },
    { word: "factbox", subcategory: "General News" },
    { word: "overview", subcategory: "General News" },
    { word: "context", subcategory: "General News" },
    { word: "background", subcategory: "General News" },
    { word: "profile", subcategory: "General News" },
    { word: "biography", subcategory: "General News" },
    { word: "information", subcategory: "General News" },
    { word: "timeline", subcategory: "General News" },
    { word: "chronology", subcategory: "General News" },
    { word: "agenda", subcategory: "General News" },
    { word: "calendar", subcategory: "General News" },
    { word: "schedule", subcategory: "General News" },
    { word: "event", subcategory: "General News" },
    { word: "press release", subcategory: "General News" },
    { word: "media advisory", subcategory: "General News" },
    { word: "public statement", subcategory: "General News" },
    { word: "official statement", subcategory: "General News" },
    { word: "declaration", subcategory: "General News" },
    { word: "policy", subcategory: "General News" },
    { word: "regulation", subcategory: "General News" },
    { word: "law", subcategory: "General News" },
    { word: "legislation", subcategory: "General News" },
    { word: "act", subcategory: "General News" },
    { word: "bill", subcategory: "General News" },
    { word: "decree", subcategory: "General News" },
    { word: "order", subcategory: "General News" },
    { word: "mandate", subcategory: "General News" },
    { word: "directive", subcategory: "General News" },
    { word: "recommendation", subcategory: "General News" },
    { word: "protocol", subcategory: "General News" },
    { word: "procedure", subcategory: "General News" },
    { word: "guidelines", subcategory: "General News" },
    { word: "rules", subcategory: "General News" },
    { word: "standards", subcategory: "General News" },
    { word: "criteria", subcategory: "General News" },
    { word: "norms", subcategory: "General News" },
    { word: "benchmark", subcategory: "General News" },
    { word: "index", subcategory: "General News" },
    { word: "indicator", subcategory: "General News" },
    { word: "metric", subcategory: "General News" },
    { word: "data", subcategory: "General News" },
    { word: "statistics", subcategory: "General News" },
    { word: "figures", subcategory: "General News" },
    { word: "trends", subcategory: "General News" },
    { word: "pattern", subcategory: "General News" },
    { word: "survey", subcategory: "General News" },
    { word: "poll", subcategory: "General News" },
    { word: "questionnaires", subcategory: "General News" },
    { word: "response", subcategory: "General News" },
    { word: "opinion", subcategory: "General News" },
    { word: "sentiment", subcategory: "General News" },
    { word: "reaction", subcategory: "General News" },
    { word: "comment", subcategory: "General News" },
    { word: "statement", subcategory: "General News" },
    { word: "position", subcategory: "General News" },
    { word: "stance", subcategory: "General News" },
    { word: "viewpoint", subcategory: "General News" },
    { word: "perspective", subcategory: "General News" },
    { word: "outlook", subcategory: "General News" },
    { word: "forecast", subcategory: "General News" },
    { word: "prediction", subcategory: "General News" },
    { word: "projections", subcategory: "General News" },
    { word: "scenario", subcategory: "General News" },
    { word: "plan", subcategory: "General News" },
    { word: "initiative", subcategory: "General News" },
    { word: "project", subcategory: "General News" },
    { word: "program", subcategory: "General News" },
    { word: "drive", subcategory: "General News" },
    { word: "effort", subcategory: "General News" },
    { word: "movement", subcategory: "General News" },
    { word: "coalition", subcategory: "General News" },
    { word: "alliance", subcategory: "General News" },
    { word: "partnership", subcategory: "General News" },
    { word: "cooperation", subcategory: "General News" },
    { word: "coordination", subcategory: "General News" },
    { word: "task force", subcategory: "General News" },
    { word: "committee", subcategory: "General News" },
    { word: "commission", subcategory: "General News" },
    { word: "board", subcategory: "General News" },
    { word: "panel", subcategory: "General News" },
    { word: "group", subcategory: "General News" },
    { word: "council", subcategory: "General News" },
    { word: "association", subcategory: "General News" },
    { word: "organization", subcategory: "General News" },
    { word: "institution", subcategory: "General News" },
    { word: "agency", subcategory: "General News" },
    { word: "body", subcategory: "General News" },
    { word: "entity", subcategory: "General News" },
    { word: "firm", subcategory: "General News" },
    { word: "company", subcategory: "General News" },
    { word: "corporation", subcategory: "General News" },
    { word: "business", subcategory: "General News" },
    { word: "industry", subcategory: "General News" },
    { word: "sector", subcategory: "General News" },
    { word: "market", subcategory: "Economic News" },
    { word: "economy", subcategory: "Economic News" },
    { word: "financial", subcategory: "Economic News" },
    { word: "economic", subcategory: "Economic News" },
    { word: "fiscal", subcategory: "Economic News" },
    { word: "monetary", subcategory: "Economic News" },
    { word: "budget", subcategory: "Economic News" },
    { word: "revenue", subcategory: "Economic News" },
    { word: "profit", subcategory: "Economic News" },
    { word: "loss", subcategory: "Economic News" },
    { word: "income", subcategory: "Economic News" },
    { word: "expenditure", subcategory: "Economic News" },
    { word: "cost", subcategory: "Economic News" },
    { word: "price", subcategory: "Economic News" },
    { word: "value", subcategory: "Economic News" },
    { word: "worth", subcategory: "Economic News" },
    { word: "capital", subcategory: "Economic News" },
    { word: "investment", subcategory: "Economic News" },
    { word: "funding", subcategory: "Economic News" },
    { word: "financing", subcategory: "Economic News" },
    { word: "loan", subcategory: "Economic News" },
    { word: "debt", subcategory: "Economic News" },
    { word: "deficit", subcategory: "Economic News" },
    { word: "surplus", subcategory: "Economic News" },
    { word: "savings", subcategory: "Economic News" },
    { word: "reserve", subcategory: "Economic News" },
    { word: "stock", subcategory: "Economic News" },
    { word: "share", subcategory: "Economic News" },
    { word: "bond", subcategory: "Economic News" },
    { word: "asset", subcategory: "Economic News" },
    { word: "liability", subcategory: "Economic News" },
    { word: "equity", subcategory: "Economic News" },
    { word: "dividend", subcategory: "Economic News" },
    { word: "return", subcategory: "Economic News" },
    { word: "yield", subcategory: "Economic News" },
    { word: "growth", subcategory: "Economic News" },
    { word: "expansion", subcategory: "Economic News" },
    { word: "progress", subcategory: "Economic News" },
    { word: "advancement", subcategory: "Economic News" },
    { word: "technology", subcategory: "Economic News" },
    { word: "science", subcategory: "Culture and Art News" },
    { word: "research", subcategory: "Culture and Art News" },
    { word: "discovery", subcategory: "Culture and Art News" },
    { word: "invention", subcategory: "Culture and Art News" },
    { word: "breakthrough", subcategory: "Culture and Art News" },
    { word: "experiment", subcategory: "Culture and Art News" },
    { word: "trial", subcategory: "Culture and Art News" },
    { word: "survey", subcategory: "Culture and Art News" },
    { word: "poll", subcategory: "Culture and Art News" },
    { word: "sample", subcategory: "Culture and Art News" },
    { word: "population", subcategory: "Culture and Art News" },
    { word: "demographic", subcategory: "Culture and Art News" },
    { word: "census", subcategory: "Culture and Art News" },
    { word: "statistic", subcategory: "Culture and Art News" },
    { word: "data", subcategory: "Culture and Art News" },
    { word: "figure", subcategory: "Culture and Art News" },
    { word: "metric", subcategory: "Culture and Art News" },
    { word: "indicator", subcategory: "Culture and Art News" },
    { word: "trend", subcategory: "Culture and Art News" },
    { word: "pattern", subcategory: "Culture and Art News" },
    { word: "analysis", subcategory: "Culture and Art News" },
    { word: "evaluation", subcategory: "Culture and Art News" },
    { word: "assessment", subcategory: "Culture and Art News" },
    { word: "audit", subcategory: "Culture and Art News" },
    { word: "inspection", subcategory: "Culture and Art News" },
    { word: "examination", subcategory: "Culture and Art News" },
    { word: "investigation", subcategory: "Culture and Art News" },
    { word: "inquiry", subcategory: "Culture and Art News" },
    { word: "probe", subcategory: "Culture and Art News" },
    { word: "scrutiny", subcategory: "Culture and Art News" },
    { word: "oversight", subcategory: "Culture and Art News" },
    { word: "regulation", subcategory: "Culture and Art News" },
    { word: "compliance", subcategory: "Culture and Art News" },
    { word: "enforcement", subcategory: "Culture and Art News" },
    { word: "law", subcategory: "Culture and Art News" },
    { word: "legislation", subcategory: "Culture and Art News" },
    { word: "policy", subcategory: "Culture and Art News" },
    { word: "rule", subcategory: "Culture and Art News" },
    { word: "guideline", subcategory: "Culture and Art News" },
    { word: "standard", subcategory: "Culture and Art News" },
    { word: "criterion", subcategory: "Culture and Art News" },
    { word: "benchmark", subcategory: "Culture and Art News" },
    { word: "measure", subcategory: "Culture and Art News" },
    { word: "procedure", subcategory: "Culture and Art News" },
    { word: "protocol", subcategory: "Culture and Art News" },
    { word: "practice", subcategory: "Culture and Art News" },
    { word: "method", subcategory: "Culture and Art News" },
    { word: "technique", subcategory: "Culture and Art News" },
    { word: "approach", subcategory: "Culture and Art News" },
    { word: "operation", subcategory: "Culture and Art News" },
    { word: "function", subcategory: "Culture and Art News" },
    { word: "task", subcategory: "Culture and Art News" },
    { word: "duty", subcategory: "Culture and Art News" },
    { word: "role", subcategory: "Culture and Art News" },
    { word: "responsibility", subcategory: "Culture and Art News" },
    { word: "accountability", subcategory: "Culture and Art News" },
    { word: "obligation", subcategory: "Culture and Art News" },
    { word: "requirement", subcategory: "Culture and Art News" },
    { word: "qualification", subcategory: "Culture and Art News" },
    { word: "eligibility", subcategory: "Culture and Art News" },
    { word: "criteria", subcategory: "Culture and Art News" },
    { word: "standard", subcategory: "Culture and Art News" },
    { word: "level", subcategory: "Culture and Art News" },
    { word: "extent", subcategory: "Culture and Art News" },
    { word: "magnitude", subcategory: "Culture and Art News" },
    { word: "intensity", subcategory: "Culture and Art News" },
    { word: "severity", subcategory: "Culture and Art News" },
    { word: "impact", subcategory: "Culture and Art News" },
    { word: "effect", subcategory: "Culture and Art News" },
    { word: "consequence", subcategory: "Culture and Art News" },
    { word: "outcome", subcategory: "Culture and Art News" },
    { word: "result", subcategory: "Culture and Art News" },
    { word: "aftermath", subcategory: "Culture and Art News" },
    { word: "influence", subcategory: "Culture and Art News" },
    { word: "leverage", subcategory: "Culture and Art News" },
    { word: "power", subcategory: "Culture and Art News" },
    { word: "control", subcategory: "Culture and Art News" },
    { word: "authority", subcategory: "Culture and Art News" },
    { word: "jurisdiction", subcategory: "Culture and Art News" },
    { word: "governance", subcategory: "Culture and Art News" },
    { word: "administration", subcategory: "Culture and Art News" },
    { word: "management", subcategory: "Culture and Art News" },
    { word: "leadership", subcategory: "Culture and Art News" },
    { word: "oversight", subcategory: "Culture and Art News" },
    { word: "supervision", subcategory: "Culture and Art News" },
    { word: "direction", subcategory: "Culture and Art News" },
    { word: "coordination", subcategory: "Culture and Art News" },
    { word: "cooperation", subcategory: "Culture and Art News" },
    { word: "collaboration", subcategory: "Culture and Art News" },
    { word: "partnership", subcategory: "Culture and Art News" },
    { word: "alliance", subcategory: "Culture and Art News" },
    { word: "coalition", subcategory: "Culture and Art News" },
    { word: "organization", subcategory: "Culture and Art News" },
    { word: "association", subcategory: "Culture and Art News" },
    { word: "group", subcategory: "Culture and Art News" },
    { word: "network", subcategory: "Culture and Art News" },
    { word: "task force", subcategory: "Culture and Art News" },
    { word: "committee", subcategory: "Culture and Art News" },
    { word: "board", subcategory: "Culture and Art News" },
    { word: "panel", subcategory: "Culture and Art News" },
    { word: "council", subcategory: "Culture and Art News" },
    { word: "assembly", subcategory: "Culture and Art News" },
    { word: "parliament", subcategory: "Culture and Art News" },
    { word: "legislature", subcategory: "Culture and Art News" },
    { word: "congress", subcategory: "Culture and Art News" },
    { word: "senate", subcategory: "Culture and Art News" },
    { word: "house", subcategory: "Culture and Art News" },
    { word: "chamber", subcategory: "Culture and Art News" },
    { word: "government", subcategory: "Culture and Art News" },
    { word: "administration", subcategory: "Culture and Art News" },
    { word: "authority", subcategory: "Culture and Art News" },
    { word: "regime", subcategory: "Culture and Art News" },
    { word: "leadership", subcategory: "Culture and Art News" },
    { word: "ruler", subcategory: "Culture and Art News" },
    { word: "leader", subcategory: "Culture and Art News" },
    { word: "head", subcategory: "Culture and Art News" },
    { word: "chief", subcategory: "Culture and Art News" },
    { word: "executive", subcategory: "Culture and Art News" },
    { word: "president", subcategory: "Culture and Art News" },
    { word: "prime minister", subcategory: "Culture and Art News" },
    { word: "minister", subcategory: "Culture and Art News" },
    { word: "official", subcategory: "Culture and Art News" },
    { word: "representative", subcategory: "Culture and Art News" },
    { word: "delegate", subcategory: "Culture and Art News" },
    { word: "ambassador", subcategory: "Culture and Art News" },
    { word: "envoy", subcategory: "Culture and Art News" },
    { word: "diplomat", subcategory: "Culture and Art News" },
    { word: "emissary", subcategory: "Culture and Art News" },
    { word: "consul", subcategory: "Culture and Art News" },
    { word: "agent", subcategory: "Culture and Art News" },
    { word: "officer", subcategory: "Culture and Art News" },
    { word: "member", subcategory: "Culture and Art News" },
    { word: "participant", subcategory: "Culture and Art News" },
    { word: "stakeholder", subcategory: "Culture and Art News" },
    { word: "shareholder", subcategory: "Culture and Art News" },
    { word: "investor", subcategory: "Culture and Art News" },
    { word: "donor", subcategory: "Culture and Art News" },
    { word: "benefactor", subcategory: "Culture and Art News" },
    { word: "sponsor", subcategory: "Culture and Art News" },
    { word: "patron", subcategory: "Culture and Art News" },
    { word: "supporter", subcategory: "Culture and Art News" },
    { word: "advocate", subcategory: "Culture and Art News" },
    { word: "proponent", subcategory: "Culture and Art News" },
    { word: "champion", subcategory: "Culture and Art News" },
    { word: "defender", subcategory: "Culture and Art News" },
    { word: "protector", subcategory: "Culture and Art News" },
    { word: "ally", subcategory: "Culture and Art News" },
    { word: "partner", subcategory: "Culture and Art News" },
    { word: "associate", subcategory: "Culture and Art News" },
    { word: "colleague", subcategory: "Culture and Art News" },
    { word: "peer", subcategory: "Culture and Art News" },
    { word: "counterpart", subcategory: "Culture and Art News" },
    { word: "rival", subcategory: "Culture and Art News" },
    { word: "opponent", subcategory: "Culture and Art News" },
    { word: "adversary", subcategory: "Culture and Art News" },
    { word: "competitor", subcategory: "Culture and Art News" },
    { word: "contender", subcategory: "Culture and Art News" },
    { word: "challenger", subcategory: "Culture and Art News" },
    { word: "enemy", subcategory: "Culture and Art News" },
    { word: "foe", subcategory: "Culture and Art News" },
    { word: "critic", subcategory: "Culture and Art News" },
    { word: "detractor", subcategory: "Culture and Art News" },
    { word: "skeptic", subcategory: "Culture and Art News" },
    { word: "cynic", subcategory: "Culture and Art News" },
    { word: "observer", subcategory: "Culture and Art News" },
    { word: "watcher", subcategory: "Culture and Art News" },
    { word: "spectator", subcategory: "Culture and Art News" },
    { word: "audience", subcategory: "Culture and Art News" },
    { word: "viewer", subcategory: "Culture and Art News" },
    { word: "listener", subcategory: "Culture and Art News" },
    { word: "reader", subcategory: "Culture and Art News" },
    { word: "participant", subcategory: "Culture and Art News" },
    { word: "attendee", subcategory: "Culture and Art News" },
    { word: "guest", subcategory: "Culture and Art News" },
    { word: "visitor", subcategory: "Culture and Art News" },
    { word: "tourist", subcategory: "Culture and Art News" },
    { word: "traveler", subcategory: "Culture and Art News" },
    { word: "commuter", subcategory: "Culture and Art News" },
    { word: "passenger", subcategory: "Culture and Art News" },
    { word: "customer", subcategory: "Culture and Art News" },
    { word: "client", subcategory: "Culture and Art News" },
    { word: "patient", subcategory: "Culture and Art News" },
    { word: "victim", subcategory: "Culture and Art News" },
    { word: "survivor", subcategory: "Culture and Art News" },
    { word: "casualty", subcategory: "Culture and Art News" },
    { word: "injury", subcategory: "Culture and Art News" },
    { word: "wound", subcategory: "Culture and Art News" },
    { word: "death", subcategory: "Culture and Art News" },
    { word: "fatality", subcategory: "Culture and Art News" },
    { word: "incident", subcategory: "Culture and Art News" },
    { word: "accident", subcategory: "Culture and Art News" },
    { word: "event", subcategory: "Culture and Art News" },
    { word: "occurrence", subcategory: "Culture and Art News" },
    { word: "happening", subcategory: "Culture and Art News" },
    { word: "episode", subcategory: "Culture and Art News" },
    { word: "scene", subcategory: "Culture and Art News" },
    { word: "act", subcategory: "Culture and Art News" },
    { word: "performance", subcategory: "Culture and Art News" },
    { word: "show", subcategory: "Culture and Art News" },
    { word: "production", subcategory: "Culture and Art News" },
    { word: "presentation", subcategory: "Culture and Art News" },
    { word: "exhibition", subcategory: "Culture and Art News" },
    { word: "display", subcategory: "Culture and Art News" },
    { word: "demonstration", subcategory: "Culture and Art News" },
    { word: "protest", subcategory: "Culture and Art News" },
    { word: "rally", subcategory: "Culture and Art News" },
    { word: "march", subcategory: "Culture and Art News" },
    { word: "parade", subcategory: "Culture and Art News" },
    { word: "festival", subcategory: "Culture and Art News" },
    { word: "celebration", subcategory: "Culture and Art News" },
    { word: "ceremony", subcategory: "Culture and Art News" },
    { word: "ritual", subcategory: "Culture and Art News" },
    { word: "tradition", subcategory: "Culture and Art News" },
    { word: "custom", subcategory: "Culture and Art News" },
    { word: "practice", subcategory: "Culture and Art News" },
    { word: "habit", subcategory: "Culture and Art News" },
    { word: "routine", subcategory: "Culture and Art News" },
    { word: "lifestyle", subcategory: "Culture and Art News" },
    { word: "culture", subcategory: "Culture and Art News" },
    { word: "heritage", subcategory: "Culture and Art News" },
    { word: "legacy", subcategory: "Culture and Art News" },
    { word: "tradition", subcategory: "Culture and Art News" },
    { word: "history", subcategory: "Culture and Art News" },
    { word: "chronicle", subcategory: "Culture and Art News" },
    { word: "record", subcategory: "Culture and Art News" },
    { word: "story", subcategory: "Culture and Art News" },
    { word: "narrative", subcategory: "Culture and Art News" },
    { word: "account", subcategory: "Culture and Art News" },
    { word: "description", subcategory: "Culture and Art News" },
    { word: "explanation", subcategory: "Culture and Art News" },
    { word: "report", subcategory: "Culture and Art News" },
    { word: "analysis", subcategory: "Culture and Art News" },
    { word: "critique", subcategory: "Culture and Art News" },
    { word: "review", subcategory: "Culture and Art News" },
    { word: "evaluation", subcategory: "Culture and Art News" },
    { word: "assessment", subcategory: "Culture and Art News" },
    { word: "interpretation", subcategory: "Culture and Art News" },
    { word: "view", subcategory: "Culture and Art News" },
    { word: "opinion", subcategory: "Culture and Art News" },
    { word: "perspective", subcategory: "Culture and Art News" },
    { word: "standpoint", subcategory: "Culture and Art News" },
    { word: "position", subcategory: "Culture and Art News" },
    { word: "attitude", subcategory: "Culture and Art News" },
    { word: "belief", subcategory: "Culture and Art News" },
    { word: "value", subcategory: "Culture and Art News" },
    { word: "principle", subcategory: "Culture and Art News" },
    { word: "standard", subcategory: "Culture and Art News" },
    { word: "norm", subcategory: "Culture and Art News" },
    { word: "ethic", subcategory: "Culture and Art News" },
    { word: "morality", subcategory: "Culture and Art News" },
    { word: "virtue", subcategory: "Culture and Art News" },
    { word: "vice", subcategory: "Culture and Art News" },
    { word: "behavior", subcategory: "Culture and Art News" },
    { word: "conduct", subcategory: "Culture and Art News" },
    { word: "action", subcategory: "Culture and Art News" },
    { word: "deed", subcategory: "Culture and Art News" },
    { word: "gesture", subcategory: "Culture and Art News" },
    { word: "movement", subcategory: "Culture and Art News" },
    { word: "posture", subcategory: "Culture and Art News" },
    { word: "pose", subcategory: "Culture and Art News" },
    { word: "expression", subcategory: "Culture and Art News" },
    { word: "reaction", subcategory: "Culture and Art News" },
    { word: "response", subcategory: "Culture and Art News" },
    { word: "reflex", subcategory: "Culture and Art News" },
    { word: "habit", subcategory: "Culture and Art News" },
    { word: "routine", subcategory: "Culture and Art News" },
    { word: "custom", subcategory: "Culture and Art News" },
    { word: "practice", subcategory: "Culture and Art News" },
    { word: "tradition", subcategory: "Culture and Art News" },
    { word: "ritual", subcategory: "Culture and Art News" },
    { word: "ceremony", subcategory: "Culture and Art News" },
    { word: "celebration", subcategory: "Culture and Art News" },
    { word: "festival", subcategory: "Culture and Art News" },
    { word: "holiday", subcategory: "Culture and Art News" },
    { word: "anniversary", subcategory: "Culture and Art News" },
    { word: "birthday", subcategory: "Culture and Art News" },
    { word: "wedding", subcategory: "Culture and Art News" },
    { word: "funeral", subcategory: "Culture and Art News" },
    { word: "memorial", subcategory: "Culture and Art News" },
    { word: "commemoration", subcategory: "Culture and Art News" },
    { word: "tribute", subcategory: "Culture and Art News" },
    { word: "remembrance", subcategory: "Culture and Art News" },
    { word: "recognition", subcategory: "Culture and Art News" },
    { word: "honor", subcategory: "Culture and Art News" },
    { word: "award", subcategory: "Culture and Art News" },
    { word: "prize", subcategory: "Culture and Art News" },
    { word: "trophy", subcategory: "Culture and Art News" },
    { word: "medal", subcategory: "Culture and Art News" },
    { word: "badge", subcategory: "Culture and Art News" },
    { word: "certificate", subcategory: "Culture and Art News" },
    { word: "diploma", subcategory: "Culture and Art News" },
    { word: "degree", subcategory: "Culture and Art News" },
    { word: "title", subcategory: "Culture and Art News" },
    { word: "rank", subcategory: "Culture and Art News" },
    { word: "status", subcategory: "Culture and Art News" },
    { word: "position", subcategory: "Culture and Art News" },
    { word: "role", subcategory: "Culture and Art News" },
    { word: "duty", subcategory: "Culture and Art News" },
    { word: "responsibility", subcategory: "Culture and Art News" },
    { word: "obligation", subcategory: "Culture and Art News" },
    { word: "commitment", subcategory: "Culture and Art News" },
    { word: "engagement", subcategory: "Culture and Art News" },
    { word: "participation", subcategory: "Culture and Art News" },
    { word: "involvement", subcategory: "Culture and Art News" },
    { word: "contribution", subcategory: "Culture and Art News" },
    { word: "input", subcategory: "Culture and Art News" },
    { word: "effort", subcategory: "Culture and Art News" },
    { word: "endeavor", subcategory: "Culture and Art News" },
    { word: "undertaking", subcategory: "Culture and Art News" },
    { word: "enterprise", subcategory: "Culture and Art News" },
    { word: "venture", subcategory: "Culture and Art News" },
    { word: "project", subcategory: "Culture and Art News" },
    { word: "initiative", subcategory: "Culture and Art News" },
    { word: "campaign", subcategory: "Culture and Art News" },
    { word: "movement", subcategory: "Culture and Art News" },
    { word: "cause", subcategory: "Culture and Art News" },
    { word: "mission", subcategory: "Culture and Art News" },
    { word: "goal", subcategory: "Culture and Art News" },
    { word: "objective", subcategory: "Culture and Art News" },
    { word: "aim", subcategory: "Culture and Art News" },
    { word: "purpose", subcategory: "Culture and Art News" },
    { word: "intention", subcategory: "Culture and Art News" },
    { word: "plan", subcategory: "Culture and Art News" },
    { word: "strategy", subcategory: "Culture and Art News" },
    { word: "tactic", subcategory: "Culture and Art News" },
    { word: "approach", subcategory: "Culture and Art News" },
    { word: "method", subcategory: "Culture and Art News" },
    { word: "technique", subcategory: "Culture and Art News" },
    { word: "procedure", subcategory: "Culture and Art News" },
    { word: "process", subcategory: "Culture and Art News" },
    { word: "operation", subcategory: "Culture and Art News" },
    { word: "activity", subcategory: "Culture and Art News" },
    { word: "action", subcategory: "Culture and Art News" },
    { word: "act", subcategory: "Culture and Art News" },
    { word: "performance", subcategory: "Culture and Art News" },
    { word: "task", subcategory: "Culture and Art News" },
    { word: "job", subcategory: "Culture and Art News" },
    { word: "assignment", subcategory: "Culture and Art News" },
    { word: "duty", subcategory: "Culture and Art News" },
    { word: "responsibility", subcategory: "Culture and Art News" },
    { word: "obligation", subcategory: "Culture and Art News" },
    { word: "requirement", subcategory: "Culture and Art News" },
    { word: "qualification", subcategory: "Culture and Art News" },
    { word: "eligibility", subcategory: "Culture and Art News" },
    { word: "criterion", subcategory: "Culture and Art News" },
    { word: "standard", subcategory: "Culture and Art News" },
    { word: "level", subcategory: "Culture and Art News" },
    { word: "extent", subcategory: "Culture and Art News" },
    { word: "degree", subcategory: "Culture and Art News" },
    { word: "magnitude", subcategory: "Culture and Art News" },
    { word: "intensity", subcategory: "Culture and Art News" },
    { word: "severity", subcategory: "Culture and Art News" },
    { word: "impact", subcategory: "Culture and Art News" },
    { word: "effect", subcategory: "Culture and Art News" },
    { word: "consequence", subcategory: "Culture and Art News" },
    { word: "outcome", subcategory: "Culture and Art News" },
    { word: "result", subcategory: "Culture and Art News" },
    { word: "aftermath", subcategory: "Culture and Art News" },
    { word: "influence", subcategory: "Culture and Art News" },
    { word: "leverage", subcategory: "Culture and Art News" },
    { word: "power", subcategory: "Culture and Art News" },
    { word: "control", subcategory: "Culture and Art News" },
    { word: "authority", subcategory: "Culture and Art News" },
    { word: "jurisdiction", subcategory: "Culture and Art News" },
    { word: "governance", subcategory: "Culture and Art News" },
    { word: "administration", subcategory: "Culture and Art News" },
    { word: "management", subcategory: "Culture and Art News" },
    { word: "leadership", subcategory: "Culture and Art News" },
    { word: "oversight", subcategory: "Culture and Art News" },
    { word: "supervision", subcategory: "Culture and Art News" },
    { word: "direction", subcategory: "Culture and Art News" },
    { word: "coordination", subcategory: "Culture and Art News" },
    { word: "cooperation", subcategory: "Culture and Art News" },
    { word: "collaboration", subcategory: "Culture and Art News" },
    { word: "partnership", subcategory: "Culture and Art News" },
    { word: "alliance", subcategory: "Culture and Art News" },
    { word: "coalition", subcategory: "Culture and Art News" },
    { word: "organization", subcategory: "Culture and Art News" },
    { word: "association", subcategory: "Culture and Art News" },
    { word: "group", subcategory: "Culture and Art News" },
    { word: "network", subcategory: "Culture and Art News" },
    { word: "task force", subcategory: "Culture and Art News" },
    { word: "committee", subcategory: "Culture and Art News" },
    { word: "board", subcategory: "Culture and Art News" },
    { word: "panel", subcategory: "Culture and Art News" },
    { word: "council", subcategory: "Culture and Art News" },
    { word: "assembly", subcategory: "Culture and Art News" },
    { word: "parliament", subcategory: "Culture and Art News" },
    { word: "legislature", subcategory: "Culture and Art News" },
    { word: "congress", subcategory: "Culture and Art News" },
    { word: "senate", subcategory: "Culture and Art News" },
    { word: "house", subcategory: "Culture and Art News" },
    { word: "chamber", subcategory: "Culture and Art News" },
    { word: "government", subcategory: "Culture and Art News" },
    { word: "administration", subcategory: "Culture and Art News" },
    { word: "authority", subcategory: "Culture and Art News" },
    { word: "regime", subcategory: "Culture and Art News" },
    { word: "leadership", subcategory: "Culture and Art News" },
    { word: "ruler", subcategory: "Culture and Art News" },
    { word: "sovereign", subcategory: "Culture and Art News" },
    { word: "monarch", subcategory: "Culture and Art News" },
    { word: "king", subcategory: "Culture and Art News" },
    { word: "queen", subcategory: "Culture and Art News" },
    { word: "prince", subcategory: "Culture and Art News" },
    { word: "princess", subcategory: "Culture and Art News" },
    { word: "duke", subcategory: "Culture and Art News" },
    { word: "duchess", subcategory: "Culture and Art News" },
    { word: "lord", subcategory: "Culture and Art News" },
    { word: "lady", subcategory: "Culture and Art News" },
    { word: "knight", subcategory: "Culture and Art News" },
    { word: "baron", subcategory: "Culture and Art News" },
    { word: "baroness", subcategory: "Culture and Art News" },
    { word: "emperor", subcategory: "Culture and Art News" },
    { word: "empress", subcategory: "Culture and Art News" },
    { word: "czar", subcategory: "Culture and Art News" },
    { word: "czarina", subcategory: "Culture and Art News" },
    { word: "chief", subcategory: "Culture and Art News" },
    { word: "head", subcategory: "Culture and Art News" },
    { word: "leader", subcategory: "Culture and Art News" },
    { word: "figurehead", subcategory: "Culture and Art News" },
    { word: "icon", subcategory: "Culture and Art News" },
    { word: "legend", subcategory: "Culture and Art News" },
    { word: "hero", subcategory: "Culture and Art News" },
    { word: "champion", subcategory: "Culture and Art News" },
    { word: "winner", subcategory: "Culture and Art News" },
    { word: "victor", subcategory: "Culture and Art News" },
    { word: "conqueror", subcategory: "Culture and Art News" },
    { word: "defender", subcategory: "Culture and Art News" },
    { word: "protector", subcategory: "Culture and Art News" },
    { word: "guardian", subcategory: "Culture and Art News" },
    { word: "patron", subcategory: "Culture and Art News" },
    { word: "advocate", subcategory: "Culture and Art News" },
    { word: "supporter", subcategory: "Culture and Art News" },
    { word: "ally", subcategory: "Culture and Art News" },
    { word: "friend", subcategory: "Culture and Art News" },
    { word: "companion", subcategory: "Culture and Art News" },
    { word: "partner", subcategory: "Culture and Art News" },
    { word: "associate", subcategory: "Culture and Art News" },
    { word: "colleague", subcategory: "Culture and Art News" },
    { word: "peer", subcategory: "Culture and Art News" },
    { word: "contemporary", subcategory: "Culture and Art News" },
    { word: "neighbor", subcategory: "Culture and Art News" },
    { word: "resident", subcategory: "Culture and Art News" },
    { word: "citizen", subcategory: "Culture and Art News" },
    { word: "inhabitant", subcategory: "Culture and Art News" },
    { word: "occupant", subcategory: "Culture and Art News" },
    { word: "tenant", subcategory: "Culture and Art News" },
    { word: "owner", subcategory: "Culture and Art News" },
    { word: "proprietor", subcategory: "Culture and Art News" },
    { word: "landlord", subcategory: "Culture and Art News" },
    { word: "landlady", subcategory: "Culture and Art News" },
    { word: "host", subcategory: "Culture and Art News" },
    { word: "hostess", subcategory: "Culture and Art News" },
    { word: "guest", subcategory: "Culture and Art News" },
    { word: "visitor", subcategory: "Culture and Art News" },
    { word: "tourist", subcategory: "Culture and Art News" },
    { word: "traveler", subcategory: "Culture and Art News" },
    { word: "explorer", subcategory: "Culture and Art News" },
    { word: "adventurer", subcategory: "Culture and Art News" },
    { word: "pioneer", subcategory: "Culture and Art News" },
    { word: "settler", subcategory: "Culture and Art News" },
    { word: "colonist", subcategory: "Culture and Art News" },
    { word: "immigrant", subcategory: "Culture and Art News" },
    { word: "emigrant", subcategory: "Culture and Art News" },
    { word: "refugee", subcategory: "Culture and Art News" },
    { word: "asylum seeker", subcategory: "Culture and Art News" },
    { word: "displaced person", subcategory: "Culture and Art News" },
    { word: "migrant", subcategory: "Culture and Art News" },
    { word: "exile", subcategory: "Culture and Art News" },
    { word: "expatriate", subcategory: "Culture and Art News" },
    { word: "nomad", subcategory: "Culture and Art News" },
    { word: "gypsy", subcategory: "Culture and Art News" },
    { word: "vagabond", subcategory: "Culture and Art News" },
    { word: "wanderer", subcategory: "Culture and Art News" },
    { word: "drifter", subcategory: "Culture and Art News" },
    { word: "vagrant", subcategory: "Culture and Art News" },
    { word: "hobo", subcategory: "Culture and Art News" },
    { word: "beggar", subcategory: "Culture and Art News" },
    { word: "panhandler", subcategory: "Culture and Art News" },
    { word: "tramp", subcategory: "Culture and Art News" },
    { word: "derelict", subcategory: "Culture and Art News" },
    { word: "street person", subcategory: "Culture and Art News" },
    { word: "homeless person", subcategory: "Culture and Art News" },
    { word: "squatter", subcategory: "Culture and Art News" },
    { word: "occupier", subcategory: "Culture and Art News" },
    { word: "protestor", subcategory: "Culture and Art News" },
    { word: "demonstrator", subcategory: "Culture and Art News" },
    { word: "activist", subcategory: "Culture and Art News" },
    { word: "campaigner", subcategory: "Culture and Art News" },
    { word: "advocate", subcategory: "Culture and Art News" },
    { word: "supporter", subcategory: "Culture and Art News" },
    { word: "ally", subcategory: "Culture and Art News" },
    { word: "friend", subcategory: "Culture and Art News" },
    { word: "companion", subcategory: "Culture and Art News" },
    { word: "partner", subcategory: "Culture and Art News" },
    { word: "associate", subcategory: "Culture and Art News" },
    { word: "colleague", subcategory: "Culture and Art News" },
    { word: "peer", subcategory: "Culture and Art News" },
    { word: "contemporary", subcategory: "Culture and Art News" },
    { word: "neighbor", subcategory: "Culture and Art News" },
    { word: "resident", subcategory: "Culture and Art News" },
    { word: "citizen", subcategory: "Culture and Art News" },
    { word: "inhabitant", subcategory: "Culture and Art News" },
    { word: "occupant", subcategory: "Culture and Art News" },
    { word: "tenant", subcategory: "Culture and Art News" },
    { word: "owner", subcategory: "Culture and Art News" },
    { word: "proprietor", subcategory: "Culture and Art News" },
    { word: "landlord", subcategory: "Culture and Art News" },
    { word: "landlady", subcategory: "Culture and Art News" },
    { word: "host", subcategory: "Culture and Art News" },
    { word: "hostess", subcategory: "Culture and Art News" },
    { word: "guest", subcategory: "Culture and Art News" },
    { word: "visitor", subcategory: "Culture and Art News" },
    { word: "tourist", subcategory: "Culture and Art News" },
    { word: "traveler", subcategory: "Culture and Art News" },
    { word: "explorer", subcategory: "Culture and Art News" },
    { word: "adventurer", subcategory: "Culture and Art News" },
    { word: "pioneer", subcategory: "Culture and Art News" },
    { word: "settler", subcategory: "Culture and Art News" },
    { word: "colonist", subcategory: "Culture and Art News" },
    { word: "immigrant", subcategory: "Culture and Art News" },
    { word: "emigrant", subcategory: "Culture and Art News" },
    { word: "refugee", subcategory: "Culture and Art News" },
    { word: "asylum seeker", subcategory: "Culture and Art News" },
    { word: "displaced person", subcategory: "Culture and Art News" },
    { word: "migrant", subcategory: "Culture and Art News" },
    { word: "exile", subcategory: "Culture and Art News" },
    { word: "expatriate", subcategory: "Culture and Art News" },
    { word: "nomad", subcategory: "Culture and Art News" },
    { word: "gypsy", subcategory: "Culture and Art News" },
    { word: "vagabond", subcategory: "Culture and Art News" },
    { word: "wanderer", subcategory: "Culture and Art News" },
    { word: "drifter", subcategory: "Culture and Art News" },
    { word: "vagrant", subcategory: "Culture and Art News" },
    { word: "hobo", subcategory: "Culture and Art News" },
    { word: "beggar", subcategory: "Culture and Art News" },
    { word: "panhandler", subcategory: "Culture and Art News" },
    { word: "tramp", subcategory: "Culture and Art News" },
    { word: "derelict", subcategory: "Culture and Art News" },
    { word: "street person", subcategory: "Culture and Art News" },
    { word: "homeless person", subcategory: "Culture and Art News" },
    { word: "squatter", subcategory: "Culture and Art News" },
    { word: "occupier", subcategory: "Culture and Art News" },
    { word: "protestor", subcategory: "Culture and Art News" },
    { word: "demonstrator", subcategory: "Culture and Art News" },
    { word: "activist", subcategory: "Culture and Art News" },
    { word: "campaigner", subcategory: "Culture and Art News" },
    { word: "advocate", subcategory: "Culture and Art News" },
    { word: "supporter", subcategory: "Culture and Art News" },
    { word: "ally", subcategory: "Culture and Art News" },
    { word: "friend", subcategory: "Culture and Art News" },
    { word: "companion", subcategory: "Culture and Art News" },
    { word: "partner", subcategory: "Culture and Art News" },
    { word: "associate", subcategory: "Culture and Art News" },
    { word: "colleague", subcategory: "Culture and Art News" },
    { word: "peer", subcategory: "Culture and Art News" },
    { word: "contemporary", subcategory: "Culture and Art News" },
    { word: "neighbor", subcategory: "Culture and Art News" },
    { word: "resident", subcategory: "Culture and Art News" },
    { word: "citizen", subcategory: "Culture and Art News" },
    { word: "inhabitant", subcategory: "Culture and Art News" },
    { word: "occupant", subcategory: "Culture and Art News" },
    { word: "tenant", subcategory: "Culture and Art News" },
    { word: "owner", subcategory: "Culture and Art News" },
    { word: "proprietor", subcategory: "Culture and Art News" },
    { word: "landlord", subcategory: "Culture and Art News" },
    { word: "landlady", subcategory: "Culture and Art News" },
    { word: "host", subcategory: "Culture and Art News" },
    { word: "hostess", subcategory: "Culture and Art News" },
    { word: "guest", subcategory: "Culture and Art News" },
    { word: "visitor", subcategory: "Culture and Art News" },
    { word: "tourist", subcategory: "Culture and Art News" },
    { word: "traveler", subcategory: "Culture and Art News" },
    { word: "explorer", subcategory: "Culture and Art News" },
    { word: "adventurer", subcategory: "Culture and Art News" },
    { word: "pioneer", subcategory: "Culture and Art News" },
    { word: "settler", subcategory: "Culture and Art News" },
    { word: "colonist", subcategory: "Culture and Art News" },
    { word: "immigrant", subcategory: "Culture and Art News" },
    { word: "emigrant", subcategory: "Culture and Art News" },
    { word: "refugee", subcategory: "Culture and Art News" },
    { word: "asylum seeker", subcategory: "Culture and Art News" },
    { word: "displaced person", subcategory: "Culture and Art News" },
    { word: "migrant", subcategory: "Culture and Art News" },
    { word: "exile", subcategory: "Culture and Art News" },
    { word: "expatriate", subcategory: "Culture and Art News" },
    { word: "nomad", subcategory: "Culture and Art News" },
    { word: "gypsy", subcategory: "Culture and Art News" },
    { word: "vagabond", subcategory: "Culture and Art News" },
    { word: "wanderer", subcategory: "Culture and Art News" },
    { word: "drifter", subcategory: "Culture and Art News" },
    { word: "vagrant", subcategory: "Culture and Art News" },
    { word: "hobo", subcategory: "Culture and Art News" },
    { word: "beggar", subcategory: "Culture and Art News" },
    { word: "panhandler", subcategory: "Culture and Art News" },
    { word: "tramp", subcategory: "Culture and Art News" },
    { word: "derelict", subcategory: "Culture and Art News" },
    { word: "street person", subcategory: "Culture and Art News" },
    { word: "homeless person", subcategory: "Culture and Art News" },
    { word: "squatter", subcategory: "Culture and Art News" },
    { word: "occupier", subcategory: "Culture and Art News" },
    { word: "protestor", subcategory: "Culture and Art News" },
    { word: "demonstrator", subcategory: "Culture and Art News" },
    { word: "activist", subcategory: "Culture and Art News" },
    { word: "campaigner", subcategory: "Culture and Art News" },
    { word: "advocate", subcategory: "Culture and Art News" },
    { word: "supporter", subcategory: "Culture and Art News" },
    { word: "ally", subcategory: "Culture and Art News" },
    { word: "friend", subcategory: "Culture and Art News" },
    { word: "companion", subcategory: "Culture and Art News" },
    { word: "partner", subcategory: "Culture and Art News" },
    { word: "associate", subcategory: "Culture and Art News" },
    { word: "colleague", subcategory: "Culture and Art News" },
    { word: "peer", subcategory: "Culture and Art News" },
    { word: "contemporary", subcategory: "Culture and Art News" },
    { word: "neighbor", subcategory: "Culture and Art News" },
    { word: "resident", subcategory: "Culture and Art News" },
    { word: "citizen", subcategory: "Culture and Art News" },
    { word: "inhabitant", subcategory: "Culture and Art News" },
    { word: "occupant", subcategory: "Culture and Art News" },
    { word: "tenant", subcategory: "Culture and Art News" },
    { word: "owner", subcategory: "Culture and Art News" },
    { word: "proprietor", subcategory: "Culture and Art News" },
    { word: "landlord", subcategory: "Culture and Art News" },
    { word: "landlady", subcategory: "Culture and Art News" },
    { word: "host", subcategory: "Culture and Art News" },
    { word: "hostess", subcategory: "Culture and Art News" },
    { word: "guest", subcategory: "Culture and Art News" },
    { word: "visitor", subcategory: "Culture and Art News" },
    { word: "tourist", subcategory: "Culture and Art News" },
    { word: "traveler", subcategory: "Culture and Art News" },
    { word: "explorer", subcategory: "Culture and Art News" },
    { word: "adventurer", subcategory: "Culture and Art News" },
    { word: "pioneer", subcategory: "Culture and Art News" },
    { word: "settler", subcategory: "Culture and Art News" },
    { word: "colonist", subcategory: "Culture and Art News" },
    { word: "immigrant", subcategory: "Culture and Art News" },
    { word: "emigrant", subcategory: "Culture and Art News" },
    { word: "refugee", subcategory: "Culture and Art News" },
    { word: "asylum seeker", subcategory: "Culture and Art News" },
    { word: "displaced person", subcategory: "Culture and Art News" },
    { word: "migrant", subcategory: "Culture and Art News" },
    { word: "exile", subcategory: "Culture and Art News" },
    { word: "expatriate", subcategory: "Culture and Art News" },
    { word: "nomad", subcategory: "Culture and Art News" },
    { word: "gypsy", subcategory: "Culture and Art News" },
    { word: "vagabond", subcategory: "Culture and Art News" },
    { word: "wanderer", subcategory: "Culture and Art News" },
    { word: "drifter", subcategory: "Culture and Art News" },
    { word: "vagrant", subcategory: "Culture and Art News" },
    { word: "hobo", subcategory: "Culture and Art News" },
    { word: "beggar", subcategory: "Culture and Art News" },
    { word: "panhandler", subcategory: "Culture and Art News" },
    { word: "tramp", subcategory: "Culture and Art News" },
    { word: "derelict", subcategory: "Culture and Art News" },
    { word: "street person", subcategory: "Culture and Art News" },
    { word: "homeless person", subcategory: "Culture and Art News" },
    { word: "squatter", subcategory: "Culture and Art News" },
    { word: "occupier", subcategory: "Culture and Art News" },
    { word: "protestor", subcategory: "Culture and Art News" },
    { word: "demonstrator", subcategory: "Culture and Art News" },
    { word: "activist", subcategory: "Culture and Art News" },
    { word: "campaigner", subcategory: "Culture and Art News" },
    { word: "advocate", subcategory: "Culture and Art News" },
    { word: "supporter", subcategory: "Culture and Art News" },
    { word: "ally", subcategory: "Culture and Art News" },
    { word: "friend", subcategory: "Culture and Art News" },
    { word: "companion", subcategory: "Culture and Art News" },
    { word: "partner", subcategory: "Culture and Art News" },
    { word: "associate", subcategory: "Culture and Art News" },
    { word: "colleague", subcategory: "Culture and Art News" },
    { word: "peer", subcategory: "Culture and Art News" },
    { word: "contemporary", subcategory: "Culture and Art News" },
    { word: "neighbor", subcategory: "Culture and Art News" },
    { word: "resident", subcategory: "Culture and Art News" },
    { word: "citizen", subcategory: "Culture and Art News" },
    { word: "inhabitant", subcategory: "Culture and Art News" },
    { word: "occupant", subcategory: "Culture and Art News" },
    { word: "tenant", subcategory: "Culture and Art News" },
    { word: "owner", subcategory: "Culture and Art News" },
    { word: "proprietor", subcategory: "Culture and Art News" },
    { word: "landlord", subcategory: "Culture and Art News" },
    { word: "landlady", subcategory: "Culture and Art News" },
    { word: "host", subcategory: "Culture and Art News" },
    { word: "hostess", subcategory: "Culture and Art News" },
    { word: "guest", subcategory: "Culture and Art News" },
    { word: "visitor", subcategory: "Culture and Art News" },
    { word: "tourist", subcategory: "Culture and Art News" },
    { word: "traveler", subcategory: "Culture and Art News" },
    { word: "explorer", subcategory: "Culture and Art News" },
    { word: "adventurer", subcategory: "Culture and Art News" },
    { word: "pioneer", subcategory: "Culture and Art News" },
    { word: "settler", subcategory: "Culture and Art News" },
    { word: "colonist", subcategory: "Culture and Art News" },
    { word: "immigrant", subcategory: "Culture and Art News" },
    { word: "emigrant", subcategory: "Culture and Art News" },
    { word: "refugee", subcategory: "Culture and Art News" },
    { word: "asylum seeker", subcategory: "Culture and Art News" },
    { word: "displaced person", subcategory: "Culture and Art News" },
    { word: "migrant", subcategory: "Culture and Art News" },
    { word: "exile", subcategory: "Culture and Art News" },
    { word: "expatriate", subcategory: "Culture and Art News" },
    { word: "nomad", subcategory: "Culture and Art News" },
    { word: "gypsy", subcategory: "Culture and Art News" },
    { word: "vagabond", subcategory: "Culture and Art News" },
    { word: "wanderer", subcategory: "Culture and Art News" },
    { word: "drifter", subcategory: "Culture and Art News" },
    { word: "vagrant", subcategory: "Culture and Art News" },
    { word: "hobo", subcategory: "Culture and Art News" },
    { word: "beggar", subcategory: "Culture and Art News" },
    { word: "panhandler", subcategory: "Culture and Art News" },
    { word: "tramp", subcategory: "Culture and Art News" },
    { word: "derelict", subcategory: "Culture and Art News" },
    { word: "street person", subcategory: "Culture and Art News" },
    { word: "homeless person", subcategory: "Culture and Art News" },
    { word: "squatter", subcategory: "Culture and Art News" },
    { word: "occupier", subcategory: "Culture and Art News" },
    { word: "protestor", subcategory: "Culture and Art News" },
    { word: "demonstrator", subcategory: "Culture and Art News" },
    { word: "activist", subcategory: "Culture and Art News" },
    { word: "campaigner", subcategory: "Culture and Art News" },
    { word: "advocate", subcategory: "Culture and Art News" },
    { word: "supporter", subcategory: "Culture and Art News" },
    { word: "ally", subcategory: "Culture and Art News" },
    { word: "friend", subcategory: "Culture and Art News" },
    { word: "companion", subcategory: "Culture and Art News" },
    { word: "partner", subcategory: "Culture and Art News" },
    { word: "associate", subcategory: "Culture and Art News" },
    { word: "colleague", subcategory: "Culture and Art News" },
    { word: "peer", subcategory: "Culture and Art News" },
    { word: "contemporary", subcategory: "Culture and Art News" },
    { word: "neighbor", subcategory: "Culture and Art News" },
    { word: "resident", subcategory: "Culture and Art News" },
    { word: "citizen", subcategory: "Culture and Art News" },
    { word: "inhabitant", subcategory: "Culture and Art News" },
    { word: "occupant", subcategory: "Culture and Art News" },
    { word: "tenant", subcategory: "Culture and Art News" },
    { word: "owner", subcategory: "Culture and Art News" },
    { word: "proprietor", subcategory: "Culture and Art News" },
    { word: "landlord", subcategory: "Culture and Art News" }
]