export const personal = 
[
    { word: "family", subcategory: "Family and Friends" },
    { word: "friend", subcategory: "Family and Friends" },
    { word: "holiday", subcategory: "Event" },
    { word: "birthday", subcategory: "Event" },
    { word: "party", subcategory: "Event" },
    { word: "dinner", subcategory: "Event" },
    { word: "celebration", subcategory: "Event" },
    { word: "event", subcategory: "Event" },
    { word: "get-together", subcategory: "Event" },
    { word: "reunion", subcategory: "Event" },
    { word: "travel", subcategory: "Event" },
    { word: "fun", subcategory: "Event" },
    { word: "memories", subcategory: "Social Media" },
    { word: "photos", subcategory: "Social Media" },
    { word: "pictures", subcategory: "Social Media" },
    { word: "love", subcategory: "Family and Friends" },
    { word: "joy", subcategory: "Family and Friends" },
    { word: "laughter", subcategory: "Family and Friends" },
    { word: "happiness", subcategory: "Family and Friends" },
    { word: "wedding", subcategory: "Event" },
    { word: "anniversary", subcategory: "Event" },
    { word: "greeting", subcategory: "Social Media" },
    { word: "chat", subcategory: "Social Media" },
    { word: "news", subcategory: "Social Media" },
    { word: "update", subcategory: "Social Media" },
    { word: "letter", subcategory: "Social Media" },
    { word: "invitation", subcategory: "Event" },
    { word: "gift", subcategory: "Event" },
    { word: "present", subcategory: "Event" },
    { word: "surprise", subcategory: "Event" },
    { word: "adventure", subcategory: "Event" },
    { word: "outing", subcategory: "Event" },
    { word: "picnic", subcategory: "Event" },
    { word: "barbecue", subcategory: "Event" },
    { word: "cookout", subcategory: "Event" },
    { word: "hike", subcategory: "Event" },
    { word: "trip", subcategory: "Event" },
    { word: "journey", subcategory: "Event" },
    { word: "exploration", subcategory: "Event" },
    { word: "experience", subcategory: "Event" },
    { word: "hobby", subcategory: "Family and Friends" },
    { word: "craft", subcategory: "Family and Friends" },
    { word: "activity", subcategory: "Event" },
    { word: "sports", subcategory: "Event" },
    { word: "exercise", subcategory: "Event" },
    { word: "game", subcategory: "Event" },
    { word: "play", subcategory: "Event" },
    { word: "relax", subcategory: "Family and Friends" },
    { word: "unwind", subcategory: "Family and Friends" },
    { word: "cozy", subcategory: "Family and Friends" },
    { word: "comfort", subcategory: "Family and Friends" },
    { word: "home", subcategory: "Family and Friends" },
    { word: "pet", subcategory: "Family and Friends" },
    { word: "garden", subcategory: "Family and Friends" },
    { word: "nature", subcategory: "Family and Friends" },
    { word: "music", subcategory: "Social Media" },
    { word: "song", subcategory: "Social Media" },
    { word: "movie", subcategory: "Social Media" },
    { word: "film", subcategory: "Social Media" },
    { word: "novel", subcategory: "Social Media" },
    { word: "story", subcategory: "Social Media" },
    { word: "series", subcategory: "Social Media" },
    { word: "season", subcategory: "Social Media" },
    { word: "episode", subcategory: "Social Media" },
    { word: "entertainment", subcategory: "Social Media" },
    { word: "show", subcategory: "Social Media" },
    { word: "concert", subcategory: "Event" },
    { word: "festival", subcategory: "Event" },
    { word: "fair", subcategory: "Event" },
    { word: "market", subcategory: "Event" },
    { word: "sale", subcategory: "Event" },
    { word: "bargain", subcategory: "Event" },
    { word: "shopping", subcategory: "Event" },
    { word: "clothes", subcategory: "Event" },
    { word: "fashion", subcategory: "Event" },
    { word: "style", subcategory: "Event" },
    { word: "trend", subcategory: "Event" },
    { word: "beauty", subcategory: "Event" },
    { word: "makeup", subcategory: "Event" },
    { word: "skincare", subcategory: "Event" },
    { word: "fitness", subcategory: "Event" },
    { word: "health", subcategory: "Event" },
    { word: "wellness", subcategory: "Event" },
    { word: "diet", subcategory: "Event" },
    { word: "food", subcategory: "Event" },
    { word: "recipe", subcategory: "Event" },
    { word: "cooking", subcategory: "Event" },
    { word: "baking", subcategory: "Event" },
    { word: "kitchen", subcategory: "Event" },
    { word: "ingredients", subcategory: "Event" },
    { word: "meal", subcategory: "Event" },
    { word: "snack", subcategory: "Event" },
    { word: "dessert", subcategory: "Event" },
    { word: "drink", subcategory: "Event" },
    { word: "coffee", subcategory: "Event" },
    { word: "tea", subcategory: "Event" },
    { word: "wine", subcategory: "Event" },
    { word: "beer", subcategory: "Event" },
    { word: "cocktail", subcategory: "Event" },
    { word: "spirit", subcategory: "Event" },
    { word: "cheers", subcategory: "Event" },
    { word: "toast", subcategory: "Event" },
    { word: "celebrate", subcategory: "Event" },
    { word: "occasion", subcategory: "Event" },
    { word: "festivity", subcategory: "Event" },
    { word: "tradition", subcategory: "Event" },
    { word: "custom", subcategory: "Event" },
    { word: "culture", subcategory: "Event" },
    { word: "heritage", subcategory: "Event" },
    { word: "roots", subcategory: "Family and Friends" },
    { word: "tree", subcategory: "Family and Friends" },
    { word: "genealogy", subcategory: "Family and Friends" },
    { word: "ancestry", subcategory: "Family and Friends" },
    { word: "lineage", subcategory: "Family and Friends" },
    { word: "relatives", subcategory: "Family and Friends" },
    { word: "siblings", subcategory: "Family and Friends" },
    { word: "cousin", subcategory: "Family and Friends" },
    { word: "aunt", subcategory: "Family and Friends" },
    { word: "uncle", subcategory: "Family and Friends" },
    { word: "grandparent", subcategory: "Family and Friends" },
    { word: "grandchild", subcategory: "Family and Friends" },
    { word: "parent", subcategory: "Family and Friends" },
    { word: "mother", subcategory: "Family and Friends" },
    { word: "father", subcategory: "Family and Friends" },
    { word: "sister", subcategory: "Family and Friends" },
    { word: "brother", subcategory: "Family and Friends" },
    { word: "spouse", subcategory: "Family and Friends" },
    { word: "partner", subcategory: "Family and Friends" },
    { word: "child", subcategory: "Family and Friends" },
    { word: "son", subcategory: "Family and Friends" },
    { word: "daughter", subcategory: "Family and Friends" },
    { word: "baby", subcategory: "Family and Friends" },
    { word: "toddler", subcategory: "Family and Friends" },
    { word: "kid", subcategory: "Family and Friends" },
    { word: "teen", subcategory: "Family and Friends" },
    { word: "youth", subcategory: "Family and Friends" },
    { word: "adult", subcategory: "Family and Friends" },
    { word: "elder", subcategory: "Family and Friends" },
    { word: "senior", subcategory: "Family and Friends" },
    { word: "citizen", subcategory: "Family and Friends" },
    { word: "neighbor", subcategory: "Family and Friends" },
    { word: "community", subcategory: "Family and Friends" },
    { word: "neighborhood", subcategory: "Family and Friends" },
    { word: "block", subcategory: "Family and Friends" },
    { word: "street", subcategory: "Family and Friends" },
    { word: "address", subcategory: "Family and Friends" },
    { word: "home", subcategory: "Family and Friends" },
    { word: "house", subcategory: "Family and Friends" },
    { word: "apartment", subcategory: "Family and Friends" },
    { word: "condo", subcategory: "Family and Friends" },
    { word: "townhouse", subcategory: "Family and Friends" },
    { word: "villa", subcategory: "Family and Friends" },
    { word: "bungalow", subcategory: "Family and Friends" },
    { word: "cottage", subcategory: "Family and Friends" },
    { word: "cabin", subcategory: "Family and Friends" },
    { word: "lodge", subcategory: "Family and Friends" },
    { word: "farm", subcategory: "Family and Friends" },
    { word: "estate", subcategory: "Family and Friends" },
    { word: "property", subcategory: "Family and Friends" },
    { word: "residence", subcategory: "Family and Friends" },
    { word: "living room", subcategory: "Family and Friends" },
    { word: "bedroom", subcategory: "Family and Friends" },
    { word: "kitchen", subcategory: "Family and Friends" },
    { word: "bathroom", subcategory: "Family and Friends" },
    { word: "garden", subcategory: "Family and Friends" },
    { word: "yard", subcategory: "Family and Friends" },
    { word: "lawn", subcategory: "Family and Friends" },
    { word: "garage", subcategory: "Family and Friends" },
    { word: "driveway", subcategory: "Family and Friends" },
    { word: "porch", subcategory: "Family and Friends" },
    { word: "balcony", subcategory: "Family and Friends" },
    { word: "deck", subcategory: "Family and Friends" },
    { word: "patio", subcategory: "Family and Friends" },
    { word: "backyard", subcategory: "Family and Friends" },
    { word: "fence", subcategory: "Family and Friends" },
    { word: "gate", subcategory: "Family and Friends" },
    { word: "door", subcategory: "Family and Friends" },
    { word: "window", subcategory: "Family and Friends" },
    { word: "roof", subcategory: "Family and Friends" },
    { word: "chimney", subcategory: "Family and Friends" },
    { word: "fireplace", subcategory: "Family and Friends" },
    { word: "hearth", subcategory: "Family and Friends" },
    { word: "mantel", subcategory: "Family and Friends" },
    { word: "shelf", subcategory: "Family and Friends" },
    { word: "cabinet", subcategory: "Family and Friends" },
    { word: "closet", subcategory: "Family and Friends" },
    { word: "drawer", subcategory: "Family and Friends" },
    { word: "furniture", subcategory: "Family and Friends" },
    { word: "sofa", subcategory: "Family and Friends" },
    { word: "couch", subcategory: "Family and Friends" },
    { word: "table", subcategory: "Family and Friends" },
    { word: "bed", subcategory: "Family and Friends" },
    { word: "mattress", subcategory: "Family and Friends" },
    { word: "pillow", subcategory: "Family and Friends" },
    { word: "blanket", subcategory: "Family and Friends" },
    { word: "sheet", subcategory: "Family and Friends" },
    { word: "duvet", subcategory: "Family and Friends" },
    { word: "quilt", subcategory: "Family and Friends" },
    { word: "comforter", subcategory: "Family and Friends" },
    { word: "rug", subcategory: "Family and Friends" },
    { word: "carpet", subcategory: "Family and Friends" },
    { word: "curtain", subcategory: "Family and Friends" },
    { word: "blind", subcategory: "Family and Friends" },
    { word: "shade", subcategory: "Family and Friends" },
    { word: "lamp", subcategory: "Family and Friends" },
    { word: "light", subcategory: "Family and Friends" },
    { word: "bulb", subcategory: "Family and Friends" },
    { word: "fan", subcategory: "Family and Friends" },
    { word: "heater", subcategory: "Family and Friends" },
    { word: "air conditioner", subcategory: "Family and Friends" },
    { word: "vent", subcategory: "Family and Friends" },
    { word: "duct", subcategory: "Family and Friends" },
    { word: "thermostat", subcategory: "Family and Friends" },
    { word: "switch", subcategory: "Family and Friends" },
    { word: "outlet", subcategory: "Family and Friends" },
    { word: "plug", subcategory: "Family and Friends" },
    { word: "cable", subcategory: "Family and Friends" },
    { word: "wire", subcategory: "Family and Friends" },
    { word: "electronics", subcategory: "Social Media" },
    { word: "TV", subcategory: "Social Media" },
    { word: "radio", subcategory: "Social Media" },
    { word: "speaker", subcategory: "Social Media" },
    { word: "headphones", subcategory: "Social Media" },
    { word: "phone", subcategory: "Social Media" },
    { word: "tablet", subcategory: "Social Media" },
    { word: "laptop", subcategory: "Social Media" },
    { word: "desktop", subcategory: "Social Media" },
    { word: "monitor", subcategory: "Social Media" },
    { word: "keyboard", subcategory: "Social Media" },
    { word: "mouse", subcategory: "Social Media" },
    { word: "printer", subcategory: "Social Media" },
    { word: "scanner", subcategory: "Social Media" },
    { word: "camera", subcategory: "Social Media" },
    { word: "recorder", subcategory: "Social Media" },
    { word: "projector", subcategory: "Social Media" },
    { word: "screen", subcategory: "Social Media" },
    { word: "DVD", subcategory: "Social Media" },
    { word: "CD", subcategory: "Social Media" },
    { word: "disc", subcategory: "Social Media" },
    { word: "USB", subcategory: "Social Media" },
    { word: "drive", subcategory: "Social Media" },
    { word: "hard drive", subcategory: "Social Media" },
    { word: "memory", subcategory: "Social Media" },
    { word: "card", subcategory: "Social Media" },
    { word: "SIM card", subcategory: "Social Media" },
    { word: "chip", subcategory: "Social Media" },
    { word: "processor", subcategory: "Social Media" },
    { word: "battery", subcategory: "Social Media" },
    { word: "charger", subcategory: "Social Media" },
    { word: "adapter", subcategory: "Social Media" },
    { word: "cable", subcategory: "Social Media" },
    { word: "cord", subcategory: "Social Media" },
    { word: "plug", subcategory: "Social Media" },
    { word: "socket", subcategory: "Social Media" },
    { word: "outlet", subcategory: "Social Media" },
    { word: "extension", subcategory: "Social Media" },
    { word: "power", subcategory: "Social Media" },
    { word: "electricity", subcategory: "Social Media" },
    { word: "network", subcategory: "Social Media" },
    { word: "Wi-Fi", subcategory: "Social Media" },
    { word: "internet", subcategory: "Social Media" },
    { word: "online", subcategory: "Social Media" },
    { word: "website", subcategory: "Social Media" },
    { word: "email", subcategory: "Social Media" },
    { word: "message", subcategory: "Social Media" },
    { word: "chat", subcategory: "Social Media" },
    { word: "text", subcategory: "Social Media" },
    { word: "call", subcategory: "Social Media" },
    { word: "voice", subcategory: "Social Media" },
    { word: "video call", subcategory: "Social Media" },
    { word: "conference", subcategory: "Social Media" },
    { word: "meeting", subcategory: "Social Media" },
    { word: "webinar", subcategory: "Social Media" },
    { word: "seminar", subcategory: "Social Media" },
    { word: "qualification", subcategory: "Social Media" },
    { word: "assignment", subcategory: "Social Media" },
    { word: "project", subcategory: "Social Media" },
    { word: "thesis", subcategory: "Social Media" },
    { word: "dissertation", subcategory: "Social Media" },
    { word: "publication", subcategory: "Social Media" },
    { word: "paper", subcategory: "Social Media" },
    { word: "journal", subcategory: "Social Media" },
    { word: "archive", subcategory: "Social Media" },
    { word: "database", subcategory: "Social Media" },
    { word: "catalog", subcategory: "Social Media" },
    { word: "index", subcategory: "Social Media" },
    { word: "reference", subcategory: "Social Media" },
    { word: "citation", subcategory: "Social Media" },
    { word: "bibliography", subcategory: "Social Media" },
    { word: "footnote", subcategory: "Social Media" },
    { word: "endnote", subcategory: "Social Media" },
    { word: "appendix", subcategory: "Social Media" },
    { word: "glossary", subcategory: "Social Media" },
    { word: "preface", subcategory: "Social Media" },
    { word: "introduction", subcategory: "Social Media" },
    { word: "chapter", subcategory: "Social Media" },
    { word: "section", subcategory: "Social Media" },
    { word: "paragraph", subcategory: "Social Media" },
    { word: "sentence", subcategory: "Social Media" },
    { word: "word", subcategory: "Social Media" },
    { word: "letter", subcategory: "Social Media" },
    { word: "alphabet", subcategory: "Social Media" },
    { word: "grammar", subcategory: "Social Media" },
    { word: "syntax", subcategory: "Social Media" },
    { word: "punctuation", subcategory: "Social Media" },
    { word: "spelling", subcategory: "Social Media" },
    { word: "vocabulary", subcategory: "Social Media" },
    { word: "dictionary", subcategory: "Social Media" },
    { word: "thesaurus", subcategory: "Social Media" },
    { word: "synonym", subcategory: "Social Media" },
    { word: "antonym", subcategory: "Social Media" },
    { word: "homonym", subcategory: "Social Media" },
    { word: "metaphor", subcategory: "Social Media" },
    { word: "simile", subcategory: "Social Media" },
    { word: "idiom", subcategory: "Social Media" },
    { word: "proverb", subcategory: "Social Media" },
    { word: "expression", subcategory: "Social Media" },
    { word: "phrase", subcategory: "Social Media" },
    { word: "saying", subcategory: "Social Media" },
    { word: "quote", subcategory: "Social Media" },
    { word: "motto", subcategory: "Social Media" },
    { word: "slogan", subcategory: "Social Media" },
    { word: "tagline", subcategory: "Social Media" },
    { word: "brand", subcategory: "Social Media" },
    { word: "logo", subcategory: "Social Media" },
    { word: "identity", subcategory: "Social Media" },
    { word: "reputation", subcategory: "Social Media" },
    { word: "character", subcategory: "Family and Friends" },
    { word: "personality", subcategory: "Family and Friends" },
    { word: "traits", subcategory: "Family and Friends" },
    { word: "attributes", subcategory: "Family and Friends" },
    { word: "qualities", subcategory: "Family and Friends" },
    { word: "strengths", subcategory: "Family and Friends" },
    { word: "weaknesses", subcategory: "Family and Friends" },
    { word: "interests", subcategory: "Family and Friends" },
    { word: "hobbies", subcategory: "Family and Friends" },
    { word: "passions", subcategory: "Family and Friends" },
    { word: "skills", subcategory: "Family and Friends" },
    { word: "abilities", subcategory: "Family and Friends" },
    { word: "talents", subcategory: "Family and Friends" },
    { word: "gifts", subcategory: "Family and Friends" },
    { word: "potential", subcategory: "Family and Friends" },
    { word: "challenge", subcategory: "Family and Friends" },
    { word: "problems", subcategory: "Family and Friends" },
    { word: "solutions", subcategory: "Family and Friends" },
    { word: "answers", subcategory: "Family and Friends" },
    { word: "questions", subcategory: "Family and Friends" },
    { word: "query", subcategory: "Family and Friends" },
    { word: "inquiry", subcategory: "Family and Friends" },
    { word: "research", subcategory: "Social Media" },
    { word: "study", subcategory: "Social Media" },
    { word: "survey", subcategory: "Social Media" },
    { word: "poll", subcategory: "Social Media" },
    { word: "data", subcategory: "Social Media" },
    { word: "statistics", subcategory: "Social Media" },
    { word: "analysis", subcategory: "Social Media" },
    { word: "report", subcategory: "Social Media" },
    { word: "presentation", subcategory: "Social Media" },
    { word: "proposal", subcategory: "Social Media" },
    { word: "plan", subcategory: "Social Media" },
    { word: "project", subcategory: "Social Media" },
    { word: "task", subcategory: "Social Media" },
    { word: "goal", subcategory: "Social Media" },
    { word: "objective", subcategory: "Social Media" },
    { word: "strategy", subcategory: "Social Media" },
    { word: "tactics", subcategory: "Social Media" },
    { word: "initiative", subcategory: "Social Media" },
    { word: "campaign", subcategory: "Social Media" },
    { word: "event", subcategory: "Social Media" },
    { word: "meeting", subcategory: "Social Media" },
    { word: "conference", subcategory: "Social Media" },
    { word: "workshop", subcategory: "Social Media" },
    { word: "seminar", subcategory: "Social Media" },
    { word: "webinar", subcategory: "Social Media" },
    { word: "training", subcategory: "Social Media" },
    { word: "development", subcategory: "Social Media" },
    { word: "growth", subcategory: "Social Media" },
    { word: "progress", subcategory: "Social Media" },
    { word: "achievement", subcategory: "Social Media" },
    { word: "success", subcategory: "Social Media" },
    { word: "failure", subcategory: "Social Media" },
    { word: "lesson", subcategory: "Social Media" },
    { word: "education", subcategory: "Social Media" },
    { word: "learning", subcategory: "Social Media" },
    { word: "training", subcategory: "Social Media" },
    { word: "development", subcategory: "Social Media" },
    { word: "career", subcategory: "Social Media" },
    { word: "job", subcategory: "Social Media" },
    { word: "occupation", subcategory: "Social Media" },
    { word: "profession", subcategory: "Social Media" },
    { word: "vocation", subcategory: "Social Media" },
    { word: "role", subcategory: "Social Media" },
    { word: "position", subcategory: "Social Media" },
    { word: "title", subcategory: "Social Media" },
    { word: "rank", subcategory: "Social Media" },
    { word: "level", subcategory: "Social Media" },
    { word: "status", subcategory: "Social Media" },
    { word: "authority", subcategory: "Social Media" },
    { word: "power", subcategory: "Social Media" },
    { word: "influence", subcategory: "Social Media" },
]
